### ISSUE TITLE
Add exact match search to metafields in products query

### ISSUE THREAD

**Issue by MohanNarayana** [reactioncommerce/api-plugin-products#39]
The products query performs a fuzzy search for `metafieldKey` and `metafieldValue`. While retaining this option to avoid behavioral changes of the API we would like to add the option to perform exact match search. A flag will be introduced as a query argument to switch between the two search options. The default search will be exact match and the user can set the flag to switch to fuzzy search.

**Comment by brent-hoover** [comment]
To not be a breaking change we need to retain the default behavior
